- id: '1551361443867'
  alias: Notifica Antifurto
  trigger:
  - entity_id: binary_sensor.antifurto
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Intrusione rilevata in casa.
      title: Allarme!
    service: notify.family_devices
- id: '1553559417043'
  alias: Accensione Luci Antifurto
  trigger:
  - entity_id: binary_sensor.antifurto
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - after: sunset
    condition: sun
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_on
