- id: '1569862394579'
  alias: Update Available Notification
  trigger:
  - entity_id: binary_sensor.updater
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
    service: notify.ios_pierfrancesco_iphonex
